language: node_js
node_js:
  - "12"

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - npm run build --prod

before_deploy:
  - docker-compose -f etc/docker/docker-compose-dev.yml build
