name: Push to registry
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: npm run build

    - name: Build the Docker image
      run: docker build . --file etc/docker/Dockerfile-dev --tag ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest

    - name: Login to docker registry
      run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

    - name: Push to docker registry
      run: docker push ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest
